# 🔢 NumPy & Matplotlib : calcul scientifique et visualisation

Bienvenue dans ce notebook consacré à **NumPy** et **Matplotlib**, le duo incontournable du calcul numérique et de la visualisation scientifique en Python. Ils sont au cœur de quasiment tout l'écosystème scientifique Python (data science, machine learning, simulation, traitement du signal, etc.), et tu vas les retrouver constamment durant ton cycle ingénieur.

Ce notebook suppose que tu es déjà à l'aise avec les bases de Python (variables, listes, boucles, fonctions). Si ce n'est pas encore le cas, reprends d'abord le notebook d'introduction à Python.

## Comment utiliser ce notebook

- Les cellules de **texte** expliquent une notion.
- Les cellules de **code** sont des exemples à exécuter (`Shift + Entrée`).
- Les cellules **✏️ Exercice** sont à faire par toi-même.
- Les encadrés **🚀 Pour aller plus loin** sont optionnels mais recommandés si tu vises un cycle ingénieur exigeant.

## Sommaire

1. [Pourquoi NumPy ?](#1)
2. [Créer des tableaux](#2)
3. [Propriétés et manipulation des tableaux](#3)
4. [Opérations vectorisées et broadcasting](#4)
5. [Statistiques et agrégations](#5)
6. [Matrices et algèbre linéaire](#6)
7. [Nombres aléatoires et simulations](#7)
8. [Pourquoi NumPy est-il si rapide ?](#8)
9. [Visualiser ses données avec Matplotlib](#9)
10. [Mini-projet final](#10)

---

<a id="1"></a>
## 1. Pourquoi NumPy ?

Les listes Python sont pratiques, mais elles ne sont **pas adaptées au calcul numérique intensif** :
- Elles sont lentes pour de grandes quantités de données.
- On ne peut pas faire d'opérations mathématiques directement dessus (ex. multiplier tous les éléments par 2).
- Elles ne représentent pas naturellement des vecteurs, matrices ou tenseurs.

**NumPy** (*Numerical Python*) résout ces problèmes en proposant un objet central : le **`ndarray`** (tableau à N dimensions), optimisé et écrit en C en interne, donc beaucoup plus rapide.

### Import de la bibliothèque

Par convention (presque universelle), on importe NumPy avec l'alias `np`.

In [2]:
import numpy as np

print(np.__version__)

2.5.0


In [2]:
# Une liste Python classique...
liste = [1, 2, 3, 4, 5]

# ... vs un tableau NumPy
tableau = np.array([1, 2, 3, 4, 5])

print(liste)
print(tableau)
print(type(tableau))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


### La différence concrète

Avec une liste, on ne peut pas multiplier directement tous les éléments par 2 sans boucle. Avec un tableau NumPy, si.

In [3]:
liste = [1, 2, 3, 4, 5]
tableau = np.array([1, 2, 3, 4, 5])

# Avec une liste, ceci ne fait pas ce qu'on veut :
print(liste * 2)   # duplique la liste, ne multiplie pas les éléments !

# Avec NumPy, c'est immédiat et naturel :
print(tableau * 2)  # multiplie chaque élément par 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


<a id="2"></a>
## 2. Créer des tableaux

### À partir de listes Python

In [4]:
vecteur = np.array([1, 2, 3])
print(vecteur)

matrice = np.array([[1, 2, 3], [4, 5, 6]])   # une liste de listes = un tableau 2D
print(matrice)

[1 2 3]
[[1 2 3]
 [4 5 6]]


### Fonctions de création rapide

NumPy propose des fonctions pratiques pour créer des tableaux courants sans tout écrire à la main.

In [5]:
print(np.zeros((2, 3)))     # tableau 2x3 rempli de zéros
print()
print(np.ones((3, 2)))      # tableau 3x2 rempli de uns
print()
print(np.eye(3))            # matrice identité 3x3
print()
print(np.full((2, 2), 7))   # tableau 2x2 rempli de 7

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[7 7]
 [7 7]]


In [6]:
print(np.arange(0, 10, 2))       # comme range() : de 0 à 10 (exclu), par pas de 2
print(np.linspace(0, 1, 5))      # 5 valeurs régulièrement espacées entre 0 et 1 (inclus)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


### ✏️ Exercice 1

Crée un tableau NumPy contenant les 10 premiers multiples de 3 (3, 6, 9, ..., 30) en utilisant `np.arange`. Puis crée une matrice identité 4x4 avec `np.eye`.

In [7]:
# Ton code ici
tab= np.arange(0, 31, 3)
tab

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

<a id="3"></a>
## 3. Propriétés et manipulation des tableaux

### Propriétés essentielles

In [8]:
matrice = np.array([[1, 2, 3], [4, 5, 6]])

print(matrice.shape)   # dimensions : (lignes, colonnes)
print(matrice.ndim)    # nombre de dimensions
print(matrice.size)    # nombre total d'éléments
print(matrice.dtype)   # type des éléments (int, float...)

(2, 3)
2
6
int64


### `reshape` : changer la forme d'un tableau

Très utile pour passer d'un vecteur à une matrice, ou changer l'organisation des données, sans changer les valeurs.

In [9]:
vecteur = np.arange(12)   # [0, 1, 2, ..., 11]
print(vecteur)

matrice = vecteur.reshape(3, 4)   # réorganise en 3 lignes, 4 colonnes
print(matrice)

matrice2 = vecteur.reshape(4, -1)  # le -1 signifie "calcule automatiquement cette dimension"
print(matrice2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### Indexation et slicing

Comme pour les listes, mais adapté aux tableaux multidimensionnels.

In [10]:
matrice = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print(matrice[0, 0])     # élément ligne 0, colonne 0
print(matrice[1, :])     # toute la ligne 1
print(matrice[:, 2])     # toute la colonne 2
print(matrice[0:2, 0:2]) # sous-matrice (2 premières lignes, 2 premières colonnes)

1
[4 5 6]
[3 6 9]
[[1 2]
 [4 5]]


### Indexation booléenne

Une des fonctionnalités les plus puissantes de NumPy : sélectionner des éléments selon une condition.

In [11]:
tableau = np.array([1, -2, 3, -4, 5, -6])

print(tableau > 0)              # tableau de booléens
print(tableau[tableau > 0])     # sélectionne uniquement les éléments positifs

tableau[tableau < 0] = 0        # remplace tous les négatifs par 0
print(tableau)

[ True False  True False  True False]
[1 3 5]
[1 0 3 0 5 0]


### ✏️ Exercice 2

Crée un tableau 1D des entiers de 1 à 20 avec `np.arange`, transforme-le en matrice 4x5 avec `reshape`, puis affiche uniquement les éléments pairs de cette matrice grâce à l'indexation booléenne.

In [16]:
# Ton code ici
tab=np.arange(1, 21)
mat = tab.reshape(4, 5)
print(mat[mat % 2 == 0])


[ 2  4  6  8 10 12 14 16 18 20]


<a id="4"></a>
## 4. Opérations vectorisées et broadcasting

### Opérations élément par élément

Toutes les opérations arithmétiques s'appliquent élément par élément, sans boucle à écrire.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)
print(a - b)
print(a * b)     # multiplication élément par élément (pas le produit matriciel !)
print(a / b)
print(a ** 2)

### Fonctions mathématiques vectorisées

NumPy fournit des équivalents vectorisés des fonctions mathématiques usuelles.

In [ ]:
angles = np.array([0, np.pi/2, np.pi])

print(np.sin(angles))
print(np.sqrt([1, 4, 9, 16]))
print(np.exp([0, 1, 2]))
print(np.log([1, np.e, np.e**2]))

### Le broadcasting

Le **broadcasting** est un mécanisme qui permet à NumPy d'effectuer des opérations entre tableaux de tailles différentes, en "étirant" virtuellement le plus petit pour qu'il corresponde au plus grand. C'est une notion clé, souvent mal comprise au début, mais extrêmement puissante.

In [ ]:
matrice = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Ajouter un scalaire à toute la matrice
print(matrice + 100)

# Ajouter un vecteur ligne à chaque ligne de la matrice (broadcasting)
vecteur_ligne = np.array([10, 20, 30])
print(matrice + vecteur_ligne)

# Ajouter un vecteur colonne à chaque colonne de la matrice
vecteur_colonne = np.array([[100], [200], [300]])
print(matrice + vecteur_colonne)

**Règle à retenir** : NumPy compare les formes (`shape`) des deux tableaux dimension par dimension, en partant de la droite. Deux dimensions sont compatibles si elles sont égales, ou si l'une d'elles vaut 1.

### ✏️ Exercice 3

Crée une matrice 3x3 de ton choix, et utilise le broadcasting pour soustraire à chaque colonne sa propre moyenne (indice : `matrice.mean(axis=0)` donne la moyenne de chaque colonne — vu en détail dans la section suivante).

In [ ]:
# Ton code ici


<a id="5"></a>
## 5. Statistiques et agrégations

NumPy propose de nombreuses fonctions pour résumer des données.

In [ ]:
donnees = np.array([4, 8, 15, 16, 23, 42])

print(donnees.sum())     # somme
print(donnees.mean())    # moyenne
print(donnees.std())     # écart-type
print(donnees.var())     # variance
print(donnees.min())     # minimum
print(donnees.max())     # maximum
print(donnees.argmax())  # indice du maximum
print(np.median(donnees))  # médiane

### Le paramètre `axis`

Pour un tableau 2D, on peut choisir de calculer les agrégations par ligne ou par colonne grâce au paramètre `axis`.
- `axis=0` : calcule le long des lignes → un résultat **par colonne**.
- `axis=1` : calcule le long des colonnes → un résultat **par ligne**.

In [ ]:
matrice = np.array([[1, 2, 3],
                     [4, 5, 6]])

print(matrice.sum())          # somme totale
print(matrice.sum(axis=0))    # somme de chaque colonne
print(matrice.sum(axis=1))    # somme de chaque ligne

print(matrice.mean(axis=0))   # moyenne de chaque colonne

### ✏️ Exercice 4

Crée une matrice 4x3 représentant les notes de 4 étudiants dans 3 matières (valeurs de ton choix). Affiche la moyenne de chaque étudiant, puis la moyenne de chaque matière.

In [ ]:
# Ton code ici


<a id="6"></a>
## 6. Matrices et algèbre linéaire

C'est le cœur de ce notebook : ces notions sont fondamentales pour la suite de tes études (mécanique, traitement du signal, automatique, machine learning, mécanique quantique...).

### Créer des matrices et la transposée

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(A)
print(A.T)   # transposée : on échange lignes et colonnes

### ⚠️ Produit matriciel vs produit élément par élément

C'est **l'erreur la plus fréquente** chez les débutants : `*` fait un produit élément par élément, alors que le vrai produit matriciel se fait avec `@` (ou `np.dot`).

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("Produit élément par élément (*) :")
print(A * B)

print("Produit matriciel (@) :")
print(A @ B)          # équivalent à np.dot(A, B) ou np.matmul(A, B)
print(np.dot(A, B))

### Déterminant, trace et rang

- Le **déterminant** indique si une matrice est inversible (déterminant ≠ 0) et représente un facteur d'échelle géométrique.
- La **trace** est la somme des éléments diagonaux.
- Le **rang** indique le nombre de lignes/colonnes linéairement indépendantes.

In [ ]:
A = np.array([[4, 2],
              [1, 3]])

print("Déterminant :", np.linalg.det(A))
print("Trace :", np.trace(A))
print("Rang :", np.linalg.matrix_rank(A))

### Inverse d'une matrice

L'inverse $A^{-1}$ d'une matrice carrée $A$ vérifie $A \cdot A^{-1} = I$ (matrice identité). Elle n'existe que si le déterminant est non nul.

In [ ]:
A = np.array([[4, 2],
              [1, 3]])

A_inv = np.linalg.inv(A)
print("Inverse de A :")
print(A_inv)

# Vérification : A @ A_inv doit donner (environ) la matrice identité
print("Vérification (A @ A_inv) :")
print(np.round(A @ A_inv, decimals=10))

### 🎯 Résolution de systèmes linéaires

Un système d'équations linéaires comme :

$$
\begin{cases} 2x + y = 5 \\ x - 3y = -1 \end{cases}
$$

peut s'écrire sous forme matricielle $Ax = b$, et se résoudre directement avec `np.linalg.solve` — **beaucoup plus stable numériquement** que de calculer l'inverse à la main.

In [ ]:
# 2x + y  = 5
# x  - 3y = -1

A = np.array([[2, 1],
              [1, -3]])
b = np.array([5, -1])

solution = np.linalg.solve(A, b)
print(f"x = {solution[0]}, y = {solution[1]}")

# Vérification
print("Vérification A @ solution :", A @ solution)

💡 **Bonne pratique** : préfère toujours `np.linalg.solve(A, b)` à `np.linalg.inv(A) @ b`. C'est plus rapide et plus précis numériquement, même si le résultat mathématique est le même.

### 🎯 Valeurs propres, vecteurs propres et diagonalisation

Pour une matrice carrée $A$, un vecteur propre $v$ (non nul) et sa valeur propre $\lambda$ associée vérifient :

$$A v = \lambda v$$

Autrement dit, appliquer $A$ à $v$ revient simplement à l'étirer/réduire par un facteur $\lambda$, sans changer sa direction.

Si $A$ possède $n$ vecteurs propres linéairement indépendants, on peut la **diagonaliser** : $A = P D P^{-1}$, où $D$ est une matrice diagonale contenant les valeurs propres, et $P$ contient les vecteurs propres en colonnes.

In [ ]:
A = np.array([[4, 1],
              [2, 3]])

valeurs_propres, vecteurs_propres = np.linalg.eig(A)

print("Valeurs propres :", valeurs_propres)
print("Vecteurs propres (en colonnes) :")
print(vecteurs_propres)

In [ ]:
# Diagonalisation : A = P @ D @ P_inv
P = vecteurs_propres
D = np.diag(valeurs_propres)
P_inv = np.linalg.inv(P)

A_reconstruite = P @ D @ P_inv
print("A reconstruite à partir de P, D, P_inv :")
print(np.round(A_reconstruite.real, decimals=10))

**Pourquoi la diagonalisation est-elle utile ?** Elle simplifie énormément certains calculs. Par exemple, calculer $A^{10}$ directement demande 9 multiplications de matrices, mais avec $A = PDP^{-1}$ :

$$A^{10} = P D^{10} P^{-1}$$

et $D^{10}$ revient juste à élever chaque valeur propre à la puissance 10 (car $D$ est diagonale) : beaucoup plus rapide !

In [ ]:
# Calcul rapide de A^10 grâce à la diagonalisation
A_puissance_10 = P @ np.diag(valeurs_propres**10) @ np.linalg.inv(P)
print("A^10 via diagonalisation :")
print(np.round(A_puissance_10.real, decimals=2))

# Comparaison avec la méthode directe
print("A^10 via numpy.linalg.matrix_power :")
print(np.linalg.matrix_power(A, 10))

### Norme, produit scalaire et produit vectoriel

- La **norme** d'un vecteur mesure sa longueur.
- Le **produit scalaire** (dot product) mesure l'alignement entre deux vecteurs.
- Le **produit vectoriel** (cross product, en 3D) donne un vecteur perpendiculaire aux deux.

In [ ]:
v1 = np.array([3, 4])
v2 = np.array([1, 2])

print("Norme de v1 :", np.linalg.norm(v1))          # ici, 5.0 (triangle 3-4-5)
print("Produit scalaire v1.v2 :", np.dot(v1, v2))

v3 = np.array([1, 0, 0])
v4 = np.array([0, 1, 0])
print("Produit vectoriel v3 x v4 :", np.cross(v3, v4))

### 🚀 Pour aller plus loin : la décomposition SVD

La **décomposition en valeurs singulières** (SVD, *Singular Value Decomposition*) généralise la diagonalisation à **toutes** les matrices (même non carrées). Elle est à la base de nombreuses techniques modernes : compression d'images, réduction de dimension (PCA), systèmes de recommandation...

Elle décompose une matrice $A$ en $A = U \Sigma V^T$.

In [ ]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])   # matrice non carrée : 3 lignes, 2 colonnes

U, S, VT = np.linalg.svd(A)

print("U (shape) :", U.shape)
print("Valeurs singulières :", S)
print("VT (shape) :", VT.shape)

### ✏️ Exercice 5 (cœur du chapitre)

1. Résous le système suivant avec `np.linalg.solve` :
$$\begin{cases} 3x + 2y - z = 1 \\ 2x - 2y + 4z = -2 \\ -x + 0{,}5y - z = 0 \end{cases}$$

2. Calcule les valeurs propres et vecteurs propres de la matrice $A = \begin{pmatrix} 2 & 0 \\ 0 & 3 \end{pmatrix}$. Que remarques-tu de particulier pour une matrice diagonale ?

3. Vérifie si la matrice $B = \begin{pmatrix} 1 & 2 \\ 2 & 4 \end{pmatrix}$ est inversible (indice : regarde son déterminant) avant d'essayer de l'inverser.

In [ ]:
# Ton code ici


<a id="7"></a>
## 7. Nombres aléatoires et simulations

Le sous-module `np.random` est très utile pour générer des données de test, simuler des expériences, ou initialiser des modèles (machine learning).

In [ ]:
rng = np.random.default_rng(seed=42)   # seed = graine, pour des résultats reproductibles

print(rng.random(5))              # 5 nombres décimaux entre 0 et 1
print(rng.integers(1, 7, size=5)) # 5 entiers entre 1 (inclus) et 7 (exclu), comme des dés
print(rng.normal(0, 1, size=5))   # 5 valeurs suivant une loi normale (moyenne 0, écart-type 1)

### Exemple : simulation de Monte Carlo

Une application classique : estimer $\pi$ en tirant des points aléatoires dans un carré et en comptant la proportion tombée dans le cercle inscrit.

In [ ]:
rng = np.random.default_rng(seed=0)

n_points = 1_000_000
x = rng.uniform(-1, 1, n_points)
y = rng.uniform(-1, 1, n_points)

distance_au_centre = x**2 + y**2
dans_le_cercle = distance_au_centre <= 1

pi_estime = 4 * dans_le_cercle.sum() / n_points
print(f"Estimation de pi : {pi_estime}")
print(f"Valeur réelle de pi : {np.pi}")

### ✏️ Exercice 6

Simule 10 000 lancers d'un dé à 6 faces avec `rng.integers`, et affiche la fréquence d'apparition de chaque valeur (indice : `np.unique(..., return_counts=True)` peut t'aider).

In [ ]:
# Ton code ici


<a id="8"></a>
## 8. Pourquoi NumPy est-il si rapide ?

NumPy doit sa rapidité à plusieurs facteurs :
- Les tableaux sont stockés en mémoire de façon **contiguë** et **homogène** (un seul type de données), contrairement aux listes Python.
- Les opérations sont exécutées par du code **compilé en C**, pas interprété ligne par ligne comme du Python pur.
- Il exploite la **vectorisation** : une seule instruction s'applique à tout un tableau, au lieu d'une boucle Python explicite.

### Comparaison pratique

In [ ]:
import time

n = 5_000_000

# Méthode 1 : boucle Python pure
liste = list(range(n))
debut = time.time()
resultat = [x * 2 for x in liste]
duree_python = time.time() - debut
print(f"Boucle Python : {duree_python:.4f} secondes")

# Méthode 2 : NumPy vectorisé
tableau = np.arange(n)
debut = time.time()
resultat = tableau * 2
duree_numpy = time.time() - debut
print(f"NumPy vectorisé : {duree_numpy:.4f} secondes")

print(f"NumPy est environ {duree_python / duree_numpy:.0f}x plus rapide ici")

**À retenir** : dès que tu manipules de grandes quantités de données numériques, essaie toujours de **vectoriser** tes calculs avec NumPy plutôt que d'écrire des boucles `for` explicites. C'est plus rapide, et généralement plus lisible.

<a id="9"></a>
## 9. Visualiser ses données avec Matplotlib

**Matplotlib** est LA bibliothèque de référence pour la visualisation en Python. Une donnée bien visualisée se comprend souvent en quelques secondes, là où un tableau de chiffres demanderait de longues minutes d'analyse. En ingénierie, tu t'en serviras pour tracer des courbes de fonctions, visualiser des signaux, illustrer des résultats de simulation, ou encore explorer un jeu de données.

Dans cette section, on va non seulement voir les bases du tracé de courbes, mais aussi **réutiliser tout ce qu'on a vu au chapitre 6 et 7** pour lui donner vie visuellement : matrices, vecteurs propres, systèmes linéaires, simulations aléatoires.

### Importer Matplotlib

Par convention, on importe le sous-module `pyplot` sous l'alias `plt`. La commande `%matplotlib inline` (une "commande magique" de Jupyter) garantit que les graphiques s'affichent directement dans le notebook.

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

print("Matplotlib est prêt !")

### 9.1 Tracer une courbe simple

Le principe de base : on donne à `plt.plot()` un tableau de valeurs `x` et un tableau de valeurs `y` de même taille, et Matplotlib relie les points. C'est là que NumPy entre en jeu : `linspace` et `arange` sont parfaits pour générer les abscisses.

In [ ]:
x = np.linspace(0, 2 * np.pi, 200)   # 200 points entre 0 et 2π
y = np.sin(x)

plt.plot(x, y)
plt.show()

### 9.2 Personnaliser un graphique

Un bon graphique scientifique doit toujours avoir un **titre**, des **labels d'axes**, et si besoin une **légende**. Matplotlib permet aussi de personnaliser couleur, épaisseur et style de ligne.

In [ ]:
x = np.linspace(0, 2 * np.pi, 200)
y = np.sin(x)

plt.plot(x, y, color="crimson", linewidth=2, linestyle="--", label="sin(x)")
plt.title("La fonction sinus")
plt.xlabel("x (radians)")
plt.ylabel("sin(x)")
plt.legend()
plt.grid(True)
plt.show()

### 9.3 Tracer plusieurs courbes

Il suffit d'appeler `plt.plot()` plusieurs fois avant `plt.show()` : Matplotlib superpose les courbes sur le même graphique.

In [ ]:
x = np.linspace(0, 2 * np.pi, 200)

plt.plot(x, np.sin(x), label="sin(x)")
plt.plot(x, np.cos(x), label="cos(x)")
plt.plot(x, np.sin(x) * np.cos(x), label="sin(x)·cos(x)")

plt.title("Quelques fonctions trigonométriques")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid(True)
plt.show()

### 9.4 Subplots : plusieurs graphiques dans une figure

`plt.subplots(nlignes, ncolonnes)` crée une grille de graphiques indépendants. C'est très utile pour comparer plusieurs résultats côte à côte.

In [ ]:
x = np.linspace(0, 2 * np.pi, 200)

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

axes[0].plot(x, np.sin(x), color="steelblue")
axes[0].set_title("sin(x)")
axes[0].grid(True)

axes[1].plot(x, np.cos(x), color="darkorange")
axes[1].set_title("cos(x)")
axes[1].grid(True)

plt.tight_layout()
plt.show()

### 9.5 D'autres types de graphiques

Selon la nature des données, un simple tracé de courbe n'est pas toujours le plus adapté. Réutilisons les simulations du chapitre 7 !

**Nuage de points (`scatter`)** : on reprend l'estimation de π par Monte Carlo, et on colore les points selon qu'ils tombent dans le cercle ou non.

In [ ]:
rng = np.random.default_rng(seed=1)
n_points = 2000
x = rng.uniform(-1, 1, n_points)
y = rng.uniform(-1, 1, n_points)
dans_le_cercle = x**2 + y**2 <= 1

plt.figure(figsize=(5, 5))
plt.scatter(x[dans_le_cercle], y[dans_le_cercle], s=5, color="mediumseagreen", label="Dans le cercle")
plt.scatter(x[~dans_le_cercle], y[~dans_le_cercle], s=5, color="lightcoral", label="Hors du cercle")

theta = np.linspace(0, 2 * np.pi, 200)
plt.plot(np.cos(theta), np.sin(theta), color="black", linewidth=1)

plt.gca().set_aspect("equal")
plt.title("Estimation de π par la méthode de Monte Carlo")
plt.legend()
plt.show()

**Diagramme en barres (`bar`)** : on reprend la simulation de dés du chapitre 7.

In [ ]:
rng = np.random.default_rng(seed=2)
lancers = rng.integers(1, 7, size=10000)
valeurs, effectifs = np.unique(lancers, return_counts=True)

plt.bar(valeurs, effectifs, color="cornflowerblue", edgecolor="black")
plt.xlabel("Valeur du dé")
plt.ylabel("Nombre d'occurrences")
plt.title("Distribution de 10 000 lancers de dé")
plt.xticks(valeurs)
plt.show()

**Histogramme (`hist`)** : idéal pour visualiser la distribution d'une variable continue.

In [ ]:
rng = np.random.default_rng(seed=3)
tailles = rng.normal(loc=170, scale=10, size=5000)  # tailles simulées, en cm

plt.hist(tailles, bins=30, color="mediumpurple", edgecolor="black")
plt.xlabel("Taille (cm)")
plt.ylabel("Effectif")
plt.title("Distribution simulée de tailles (loi normale)")
plt.show()

💡 Il existe aussi `plt.pie()` pour les diagrammes circulaires, mais ils sont peu utilisés en contexte scientifique/ingénierie (les diagrammes en barres sont presque toujours plus lisibles pour comparer des quantités).

### 9.6 Visualiser une matrice avec `imshow`

Une matrice peut se visualiser directement comme une image ("heatmap"), où la couleur de chaque case représente sa valeur. Très utile pour inspecter rapidement une grande matrice (matrice de corrélation, image, résultat de simulation...).

In [ ]:
A = np.random.default_rng(42).integers(0, 10, size=(5, 5))

plt.imshow(A, cmap="viridis")
plt.colorbar(label="Valeur")
plt.title("Visualisation d'une matrice 5x5")

# On peut même superposer les valeurs numériques sur chaque case
for i in range(5):
    for j in range(5):
        plt.text(j, i, A[i, j], ha="center", va="center", color="white")

plt.show()

### 9.7 Visualiser des vecteurs avec `quiver`

`plt.quiver()` dessine des flèches, parfait pour représenter des vecteurs dans le plan.

In [ ]:
origine = np.array([0, 0])
v1 = np.array([3, 2])
v2 = np.array([-1, 3])

plt.figure(figsize=(5, 5))
plt.quiver(*origine, *v1, angles="xy", scale_units="xy", scale=1, color="crimson", label="v1")
plt.quiver(*origine, *v2, angles="xy", scale_units="xy", scale=1, color="steelblue", label="v2")

plt.xlim(-3, 5)
plt.ylim(-1, 5)
plt.axhline(0, color="gray", linewidth=0.5)
plt.axvline(0, color="gray", linewidth=0.5)
plt.gca().set_aspect("equal")
plt.grid(True)
plt.legend()
plt.title("Deux vecteurs dans le plan")
plt.show()

### 9.8 🚀 Le grand moment : visualiser une transformation linéaire et ses vecteurs propres

C'est ici que NumPy et Matplotlib se combinent pour révéler quelque chose de vraiment parlant. On applique une matrice $A$ à tous les points d'un **cercle unité** : le cercle devient une **ellipse**. On superpose ensuite les **vecteurs propres** de $A$.

Tu vas observer quelque chose de remarquable : les vecteurs propres sont exactement les directions le long desquelles le cercle est étiré pour former l'ellipse — ce sont les seules directions que la transformation ne fait pas "tourner", elle les étire seulement (d'un facteur égal à la valeur propre associée).

In [ ]:
A = np.array([[2, 1],
              [1, 2]])

theta = np.linspace(0, 2 * np.pi, 200)
cercle = np.array([np.cos(theta), np.sin(theta)])   # points du cercle unité
ellipse = A @ cercle                                  # image du cercle par A

valeurs_propres, vecteurs_propres = np.linalg.eig(A)

plt.figure(figsize=(6, 6))
plt.plot(cercle[0], cercle[1], color="gray", linestyle="--", label="Cercle unité")
plt.plot(ellipse[0], ellipse[1], color="crimson", label="Image par A (ellipse)")

for i in range(2):
    v = vecteurs_propres[:, i]
    lam = valeurs_propres[i]
    # le vecteur propre original (en bleu)
    plt.quiver(0, 0, v[0], v[1], angles="xy", scale_units="xy", scale=1,
               color="steelblue", width=0.012)
    # le vecteur propre étiré par sa valeur propre (en vert, doit tomber sur l'ellipse)
    plt.quiver(0, 0, lam * v[0], lam * v[1], angles="xy", scale_units="xy", scale=1,
               color="darkgreen", width=0.008)

plt.gca().set_aspect("equal")
plt.grid(True)
plt.legend()
plt.title("Le cercle unité transformé par A, et ses vecteurs propres")
plt.show()

print("Valeurs propres :", valeurs_propres)

### 9.9 Visualiser la résolution d'un système linéaire

On reprend le système du chapitre 6 : $2x + y = 5$ et $x - 3y = -1$. Chaque équation représente une droite ; la solution du système est leur **point d'intersection**.

In [ ]:
x = np.linspace(-2, 6, 100)
y1 = 5 - 2 * x           # à partir de 2x + y = 5
y2 = (x + 1) / 3          # à partir de x - 3y = -1

A = np.array([[2, 1], [1, -3]])
b = np.array([5, -1])
solution = np.linalg.solve(A, b)

plt.plot(x, y1, label="2x + y = 5")
plt.plot(x, y2, label="x - 3y = -1")
plt.scatter(*solution, color="black", zorder=5,
            label=f"Solution ({solution[0]:.2f}, {solution[1]:.2f})")

plt.axhline(0, color="gray", linewidth=0.5)
plt.axvline(0, color="gray", linewidth=0.5)
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid(True)
plt.title("Résolution graphique d'un système linéaire")
plt.show()

### 9.10 🚀 Formes quadratiques en 3D : le signe des valeurs propres se voit !

Encore une belle connexion avec le chapitre 6. Pour une matrice $A$, on peut définir la fonction $f(x, y) = \begin{pmatrix} x & y \end{pmatrix} A \begin{pmatrix} x \\ y \end{pmatrix}$ (une "forme quadratique"). La forme de sa surface dépend directement du **signe des valeurs propres** de $A$ :
- Si toutes les valeurs propres sont **positives** → la surface est un "bol" convexe (comme un minimum).
- Si les valeurs propres ont des **signes opposés** → la surface est un "point-selle" (comme un col de montagne).

In [ ]:
A_convexe = np.array([[3, 0], [0, 2]])   # valeurs propres : 3 et 2 (toutes positives)
A_selle = np.array([[1, 0], [0, -1]])      # valeurs propres : 1 et -1 (signes opposés)

x = np.linspace(-2, 2, 50)
y = np.linspace(-2, 2, 50)
X, Y = np.meshgrid(x, y)

def forme_quadratique(A, X, Y):
    return A[0, 0] * X**2 + (A[0, 1] + A[1, 0]) * X * Y + A[1, 1] * Y**2

Z_convexe = forme_quadratique(A_convexe, X, Y)
Z_selle = forme_quadratique(A_selle, X, Y)

fig = plt.figure(figsize=(11, 5))

ax1 = fig.add_subplot(1, 2, 1, projection="3d")
ax1.plot_surface(X, Y, Z_convexe, cmap="viridis")
ax1.set_title(f"Valeurs propres {np.linalg.eigvals(A_convexe)} → convexe")

ax2 = fig.add_subplot(1, 2, 2, projection="3d")
ax2.plot_surface(X, Y, Z_selle, cmap="coolwarm")
ax2.set_title(f"Valeurs propres {np.linalg.eigvals(A_selle)} → point-selle")

plt.tight_layout()
plt.show()

### 9.11 Autres graphiques 3D : une courbe paramétrique

Au-delà des surfaces, on peut aussi tracer des courbes en 3D avec `ax.plot()`. Exemple classique : une hélice.

In [ ]:
fig = plt.figure(figsize=(6, 6))
ax = fig.add_subplot(projection="3d")

t = np.linspace(0, 6 * np.pi, 300)
x = np.cos(t)
y = np.sin(t)
z = t

ax.plot(x, y, z, color="darkorange")
ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_zlabel("z")
ax.set_title("Une hélice en 3D")
plt.show()

### 9.12 Sauvegarder une figure

`plt.savefig()` enregistre le dernier graphique tracé dans un fichier (PNG, PDF, SVG...). À appeler **avant** `plt.show()`.

In [ ]:
x = np.linspace(0, 10, 100)
plt.plot(x, np.sin(x), color="teal")
plt.title("Figure à sauvegarder")
plt.savefig("ma_figure.png", dpi=150, bbox_inches="tight")
plt.show()

print("Figure sauvegardée sous 'ma_figure.png'")

### ✏️ Exercice 7 (cœur du chapitre)

1. Trace la courbe de la fonction $f(x) = x^3 - 3x$ pour $x$ entre -3 et 3, avec un titre, des labels d'axes et une grille.
2. Sur le **même graphique**, ajoute la courbe de sa dérivée $f'(x) = 3x^2 - 3$, dans une couleur différente, avec une légende pour distinguer les deux courbes.
3. Crée une figure à **deux sous-graphiques côte à côte** : à gauche, un histogramme de 1000 valeurs tirées d'une loi normale (`rng.normal`) ; à droite, ces mêmes valeurs triées et tracées comme une courbe.
4. **Bonus** : reprends la matrice $A = \begin{pmatrix} 3 & 1 \\ 1 & 3 \end{pmatrix}$, calcule ses vecteurs propres avec `np.linalg.eig`, puis visualise comment elle transforme le cercle unité (comme à la section 9.8).

In [ ]:
# Ton code ici


<a id="10"></a>
## 10. Mini-projet final : analyse d'un système physique

### Contexte

On étudie un petit réseau de 3 masses reliées par des ressorts. La matrice de raideur du système est :

$$
K = \begin{pmatrix} 2 & -1 & 0 \\ -1 & 2 & -1 \\ 0 & -1 & 2 \end{pmatrix}
$$

### Cahier des charges

1. Crée la matrice $K$ avec NumPy.
2. Calcule ses valeurs propres et vecteurs propres avec `np.linalg.eig`. En mécanique, les valeurs propres de ce type de matrice sont liées aux **fréquences propres** (modes de vibration) du système.
3. Vérifie que $K$ est bien inversible (calcule son déterminant).
4. On applique un vecteur de forces $F = \begin{pmatrix} 1 \\ 0 \\ -1 \end{pmatrix}$ sur le système. Résous $K x = F$ avec `np.linalg.solve` pour trouver le déplacement $x$ de chaque masse à l'équilibre.
5. **Bonus (algèbre)** : vérifie numériquement que $K = P D P^{-1}$ en reconstruisant $K$ à partir de ses valeurs et vecteurs propres (comme fait plus haut dans le chapitre 6).
6. **Visualisation** : affiche la matrice $K$ avec `plt.imshow()`, comme vu au chapitre 9.
7. **Visualisation** : trace un diagramme en barres (`plt.bar`) du déplacement $x$ de chacune des 3 masses à l'équilibre.
8. **Bonus (visualisation)** : chacun des 3 vecteurs propres de $K$ représente un "mode de vibration" du système. Pour chaque mode, trace un graphique montrant le déplacement relatif des 3 masses (par exemple avec `plt.plot(vecteur_propre, marker="o")`), afin de visualiser comment les masses oscillent les unes par rapport aux autres dans ce mode.

À toi de jouer !

In [ ]:
# Ton code ici

K = np.array([
    # à compléter
])



---

## 🎉 Bravo !

Tu maîtrises maintenant les fondamentaux de NumPy **et** de Matplotlib : création et manipulation de tableaux, opérations vectorisées, broadcasting, statistiques, algèbre linéaire (produit matriciel, déterminant, inverse, résolution de systèmes, diagonalisation), et visualisation (courbes, subplots, matrices, vecteurs, graphiques 3D).

Ces notions reviendront très régulièrement dans tes cours de cycle ingénieur : mécanique, automatique, traitement du signal, optimisation, machine learning...

Pour aller plus loin :
- Documentation officielle : [numpy.org/doc](https://numpy.org/doc/stable/) et [matplotlib.org](https://matplotlib.org/stable/)
- Explore ensuite **SciPy**, qui étend NumPy avec des outils scientifiques plus avancés (optimisation, équations différentielles, traitement du signal), et **Pandas** pour manipuler des données tabulaires.
- Pour des graphiques plus esthétiques par défaut, jette un œil à **Seaborn**, qui s'appuie sur Matplotlib.

Bonne continuation ! 🔢📈